"""
Intervention strategy data models for PRISM.

These models represent the output of the Intervention Generator —
structured, actionable strategies produced by Gemini 2.5 Flash
in response to a situation analysis.

Each intervention strategy contains:
- A set of concrete actions with owners and timelines
- Resource requirements
- Expected outcomes
- Risk considerations

Multiple strategies are always generated to give decision makers
real choices rather than a single recommendation.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class StrategyType(str, Enum):
    """Classification of intervention by time horizon."""

    IMMEDIATE = "immediate"
    SHORT_TERM = "short_term"
    LONG_TERM = "long_term"


class CostLevel(str, Enum):
    """Qualitative cost classification."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"


class InterventionAction(BaseModel):
    """A single concrete action within an intervention strategy."""

    action_id: str
    title: str
    description: str
    responsible_party: str
    timeline_days: int = Field(ge=0)
    estimated_cost: CostLevel
    dependencies: list[str] = Field(default_factory=list)
    success_metric: str


class ExpectedOutcome(BaseModel):
    """Expected outcome of an intervention strategy."""

    metric: str
    baseline_value: str
    expected_value: str
    timeframe: str
    confidence: float = Field(ge=0.0, le=1.0)


class InterventionStrategy(BaseModel):
    """
    A single intervention strategy generated by PRISM.

    Each strategy represents a coherent set of actions that
    together address the identified root causes. Multiple strategies
    are always generated — from quick wins to comprehensive solutions.
    """

    id: str | None = None
    analysis_id: str
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    # Strategy classification
    title: str
    description: str
    strategy_type: StrategyType
    target_root_causes: list[str] = Field(default_factory=list)

    # Actions
    actions: list[InterventionAction] = Field(default_factory=list)

    # Resources and feasibility
    total_estimated_cost: CostLevel
    implementation_complexity: str
    required_authorities: list[str] = Field(default_factory=list)
    prerequisites: list[str] = Field(default_factory=list)

    # Expected outcomes
    expected_outcomes: list[ExpectedOutcome] = Field(default_factory=list)
    primary_beneficiaries: str
    estimated_population_impacted: str

    # Risk considerations
    risks: list[str] = Field(default_factory=list)
    trade_offs: list[str] = Field(default_factory=list)

    # Scoring (set by simulation in Phase 7)
    prism_score: float | None = None
    rank: int | None = None

    # Gemini reasoning
    gemini_rationale: str = ""

    def to_firestore_dict(self) -> dict[str, Any]:
        """Serialize to Firestore-compatible dictionary."""
        return self.model_dump(mode="json", exclude_none=False)


class GenerateInterventionsRequest(BaseModel):
    """Request to generate intervention strategies for an analysis."""

    analysis_id: str = Field(description="ID of the situation analysis to address")
    num_strategies: int = Field(
        default=3,
        ge=2,
        le=4,
        description="Number of intervention strategies to generate",
    )


class InterventionListResponse(BaseModel):
    """API response for a list of intervention strategies."""

    strategies: list[InterventionStrategy]
    analysis_id: str
    total: int


class InterventionResponse(BaseModel):
    """API response for a single intervention strategy."""

    strategy: InterventionStrategy